import 'package:flutter/material.dart';
import 'package:sample_app/ui/core/example_item.dart';

/// Ejemplos organizados por categoría.
final Map<String, List<ExampleItem>> exampleCategories = {
  'Ejercicios': [
    ExampleItem(
      id: 72,
      title: 'Calculadora',
      subtitle: 'Suma, resta, multiplicación y división',
      icon: Icons.calculate,
      route: '/exercise_calculator',
      category: 'Ejercicios',
    ),
    // apod 
    ExampleItem(
      id: 73,
      title: 'Astronomy Picture of the Day',
      subtitle: 'Fetch de API REST, parsing, imagen y texto',
      icon: Icons.image,
      route: '/exercise_apod',
      category: 'Ejercicios',
    ),
  ],
  'Conceptos de Widget': [
    ExampleItem(
      id: 100,
      title: 'StatelessWidget vs StatefulWidget',
      subtitle: 'Estado local vs datos del padre, reconstrucciones',
      icon: Icons.widgets,
      route: '/stateless_vs_stateful',
      category: 'Conceptos de Widget',
    ),
    ExampleItem(
      id: 101,
      title: 'Ciclo de vida del Widget',
      subtitle: 'initState, didUpdateWidget, dispose, rebuild',
      icon: Icons.autorenew,
      route: '/widget_lifecycle',
      category: 'Conceptos de Widget',
    ),
    ExampleItem(
      id: 102,
      title: 'Keys — Identidad de widgets',
      subtitle: 'ValueKey, ObjectKey, qué pasa SIN keys',
      icon: Icons.vpn_key,
      route: '/keys',
      category: 'Conceptos de Widget',
    ),
    ExampleItem(
      id: 103,
      title: 'Árbol Widget → Element → RenderObject',
      subtitle: 'Los tres árboles internos de Flutter',
      icon: Icons.account_tree,
      route: '/widget_tree',
      category: 'Conceptos de Widget',
    ),
    ExampleItem(
      id: 104,
      title: 'const y rendimiento',
      subtitle: 'Evitar reconstrucciones innecesarias con const',
      icon: Icons.speed,
      route: '/const_widget',
      category: 'Conceptos de Widget',
    ),
    ExampleItem(
      id: 105,
      title: 'Composición — Widgets que hacen una cosa',
      subtitle: 'Componer widgets simples para crear UI compleja',
      icon: Icons.extension,
      route: '/composition',
      category: 'Conceptos de Widget',
    ),
    ExampleItem(
      id: 106,
      title: 'Modelo declarativo — Describe QUÉ, no CÓMO',
      subtitle: 'Declarativo vs imperativo, setState reconstruye todo',
      icon: Icons.description,
      route: '/declarative_model',
      category: 'Conceptos de Widget',
    ),
    ExampleItem(
      id: 107,
      title: 'Optimización de reconstrucciones',
      subtitle: 'const, ValueNotifier, ValueListenableBuilder',
      icon: Icons.trending_up,
      route: '/rebuild_optimization',
      category: 'Conceptos de Widget',
    ),
  ],
  'Layout & Estructura': [
    ExampleItem(
      id: 1,
      title: 'Container & BoxDecoration',
      subtitle: 'Padding, margin, border, gradient, shadow',
      icon: Icons.crop_square,
      route: '/container',
      category: 'Layout & Estructura',
    ),
    ExampleItem(
      id: 2,
      title: 'Row & Column',
      subtitle: 'MainAxisAlignment, CrossAxisAlignment, Expanded',
      icon: Icons.view_column,
      route: '/row_column',
      category: 'Layout & Estructura',
    ),
    ExampleItem(
      id: 3,
      title: 'Stack & Positioned',
      subtitle: 'Capas superpuestas, badges, overlays',
      icon: Icons.layers,
      route: '/stack',
      category: 'Layout & Estructura',
    ),
    ExampleItem(
      id: 4,
      title: 'ListView',
      subtitle: 'Listas scrollables, builder, separadores',
      icon: Icons.view_list,
      route: '/listview',
      category: 'Layout & Estructura',
    ),
    ExampleItem(
      id: 5,
      title: 'GridView',
      subtitle: 'Grillas, crossAxisCount, aspect ratio',
      icon: Icons.grid_view,
      route: '/gridview',
      category: 'Layout & Estructura',
    ),
  ],
  'Navegación': [
    ExampleItem(
      id: 6,
      title: 'Navegación entre pantallas',
      subtitle: 'push, pop, argumentos, resultado',
      icon: Icons.navigate_next,
      route: '/navigation',
      category: 'Navegación',
    ),
    ExampleItem(
      id: 7,
      title: 'BottomNavigationBar',
      subtitle: 'Navegación por tabs inferior',
      icon: Icons.navigation,
      route: '/bottom_nav',
      category: 'Navegación',
    ),
    ExampleItem(
      id: 8,
      title: 'TabBar & TabBarView',
      subtitle: 'Pestañas deslizables con TabController',
      icon: Icons.tab,
      route: '/tabbar',
      category: 'Navegación',
    ),
    ExampleItem(
      id: 9,
      title: 'Drawer',
      subtitle: 'Menú lateral NavigationDrawer',
      icon: Icons.menu,
      route: '/drawer',
      category: 'Navegación',
    ),
  ],
  'Listas': [
    ExampleItem(
      id: 40,
      title: 'Lista genérica',
      subtitle: 'ListView.builder, ListTile, SnackBar al tocar',
      icon: Icons.list,
      route: '/generic_list',
      category: 'Listas',
    ),
    ExampleItem(
      id: 41,
      title: 'Lista con items custom',
      subtitle: 'Card, CircleAvatar, Chip, filas personalizadas',
      icon: Icons.contact_page,
      route: '/custom_list',
      category: 'Listas',
    ),
    ExampleItem(
      id: 42,
      title: 'Lista desplegable',
      subtitle: 'ExpansionTile, secciones que se abren y cierran',
      icon: Icons.expand,
      route: '/expandable_list',
      category: 'Listas',
    ),
    ExampleItem(
      id: 43,
      title: 'Lista tipo checklist',
      subtitle: 'CheckboxListTile, progreso, tachar completados',
      icon: Icons.checklist,
      route: '/checklist_list',
      category: 'Listas',
    ),
  ],
  'Entrada del usuario': [
    ExampleItem(
      id: 10,
      title: 'TextField & Form',
      subtitle: 'Validación, TextFormField, form key',
      icon: Icons.edit,
      route: '/form',
      category: 'Entrada del usuario',
    ),
    ExampleItem(
      id: 11,
      title: 'Checkbox, Switch, Radio, Slider',
      subtitle: 'Controles de selección y sus estados',
      icon: Icons.toggle_on,
      route: '/controls',
      category: 'Entrada del usuario',
    ),
    ExampleItem(
      id: 12,
      title: 'GestureDetector',
      subtitle: 'Tap, doubleTap, longPress, pan, zoom',
      icon: Icons.touch_app,
      route: '/gesture',
      category: 'Entrada del usuario',
    ),
  ],
  'Estado': [
    ExampleItem(
      id: 13,
      title: 'setState',
      subtitle: 'Estado local con StatefulWidget',
      icon: Icons.refresh,
      route: '/setstate',
      category: 'Estado',
    ),
    ExampleItem(
      id: 14,
      title: 'ValueNotifier',
      subtitle: 'Estado reactivo sin rebuild completo',
      icon: Icons.notifications_active,
      route: '/value_notifier',
      category: 'Estado',
    ),
    ExampleItem(
      id: 15,
      title: 'InheritedWidget',
      subtitle: 'Estado compartido por el árbol de widgets',
      icon: Icons.account_tree,
      route: '/inherited_widget',
      category: 'Estado',
    ),
  ],
  'Animación': [
    ExampleItem(
      id: 16,
      title: 'Implicit Animations',
      subtitle: 'AnimatedContainer, AnimatedOpacity, etc.',
      icon: Icons.animation,
      route: '/implicit_animation',
      category: 'Animación',
    ),
    ExampleItem(
      id: 17,
      title: 'Hero Animation',
      subtitle: 'Transiciones compartidas entre pantallas',
      icon: Icons.local_fire_department,
      route: '/hero',
      category: 'Animación',
    ),
    ExampleItem(
      id: 18,
      title: 'Explicit Animations',
      subtitle: 'AnimationController, Tween, Curves',
      icon: Icons.auto_fix_high,
      route: '/explicit_animation',
      category: 'Animación',
    ),
  ],
  'Visual & Temas': [
    ExampleItem(
      id: 19,
      title: 'Icons & Images',
      subtitle: 'Material icons, imágenes de red, placeholder',
      icon: Icons.image,
      route: '/icons_images',
      category: 'Visual & Temas',
    ),
    ExampleItem(
      id: 20,
      title: 'Themes',
      subtitle: 'ThemeData, colorScheme, claro/oscuro',
      icon: Icons.palette,
      route: '/themes',
      category: 'Visual & Temas',
    ),
    ExampleItem(
      id: 21,
      title: 'CustomPainter',
      subtitle: 'Canvas API, líneas, círculos, gráficos',
      icon: Icons.brush,
      route: '/custom_painter',
      category: 'Visual & Temas',
    ),
  ],
  'Datos asíncronos': [
    ExampleItem(
      id: 22,
      title: 'FutureBuilder',
      subtitle: 'Loading → Data/Error, carga asíncrona',
      icon: Icons.hourglass_top,
      route: '/future_builder',
      category: 'Datos asíncronos',
    ),
    ExampleItem(
      id: 23,
      title: 'StreamBuilder',
      subtitle: 'Datos en tiempo real, stopwatch, countdown',
      icon: Icons.stream,
      route: '/stream_builder',
      category: 'Datos asíncronos',
    ),
    ExampleItem(
      id: 24,
      title: 'HTTP & JSON',
      subtitle: 'Fetch de API REST, parsing, lista dinámica',
      icon: Icons.cloud_download,
      route: '/http_json',
      category: 'Datos asíncronos',
    ),
  ],
  'Material Design': [
    ExampleItem(
      id: 25,
      title: 'Cards & Elevation',
      subtitle: 'Card, InkWell, sombras, elevación',
      icon: Icons.credit_card,
      route: '/cards',
      category: 'Material Design',
    ),
    ExampleItem(
      id: 26,
      title: 'Dialogs & Snackbars',
      subtitle: 'AlertDialog, Snackbar, BottomSheet',
      icon: Icons.chat_bubble,
      route: '/dialogs',
      category: 'Material Design',
    ),
    ExampleItem(
      id: 27,
      title: 'SliverAppBar',
      subtitle: 'Collapse/expand con CustomScrollView',
      icon: Icons.vertical_align_top,
      route: '/sliver',
      category: 'Material Design',
    ),
    ExampleItem(
      id: 28,
      title: 'Chips',
      subtitle: 'Chip, InputChip, FilterChip, ChoiceChip',
      icon: Icons.label,
      route: '/chips',
      category: 'Material Design',
    ),
  ],
  'Interacción avanzada': [
    ExampleItem(
      id: 29,
      title: 'Draggable & DragTarget',
      subtitle: 'Mover elementos entre zonas',
      icon: Icons.drag_indicator,
      route: '/drag_drop',
      category: 'Interacción avanzada',
    ),
    ExampleItem(
      id: 30,
      title: 'Dismissible',
      subtitle: 'Swipe to delete con confirmación',
      icon: Icons.delete_sweep,
      route: '/dismissible',
      category: 'Interacción avanzada',
    ),
    ExampleItem(
      id: 31,
      title: 'ReorderableListView',
      subtitle: 'Long press + drag para reordenar',
      icon: Icons.reorder,
      route: '/reorderable',
      category: 'Interacción avanzada',
    ),
  ],
  'API REST': [
    ExampleItem(
      id: 63,
      title: 'GET — Listar recursos',
      subtitle: 'Fetch de lista, pull-to-refresh, errores',
      icon: Icons.list_alt,
      route: '/api_get_list',
      category: 'API REST',
    ),
    ExampleItem(
      id: 64,
      title: 'GET — Detalle de recurso',
      subtitle: 'Master-detail, navegación con argumentos',
      icon: Icons.description,
      route: '/api_get_detail',
      category: 'API REST',
    ),
    ExampleItem(
      id: 65,
      title: 'POST — Crear recurso',
      subtitle: 'Formulario, validación, jsonEncode',
      icon: Icons.add_circle,
      route: '/api_post',
      category: 'API REST',
    ),
    ExampleItem(
      id: 66,
      title: 'PUT — Actualizar recurso',
      subtitle: 'Carga, edición, comparación antes/después',
      icon: Icons.edit,
      route: '/api_put',
      category: 'API REST',
    ),
    ExampleItem(
      id: 67,
      title: 'DELETE — Eliminar recurso',
      subtitle: 'Swipe, confirmación, SnackBar deshacer',
      icon: Icons.delete,
      route: '/api_delete',
      category: 'API REST',
    ),
    ExampleItem(
      id: 68,
      title: 'Paginación',
      subtitle: 'Scroll infinito, carga progresiva',
      icon: Icons.more_horiz,
      route: '/api_pagination',
      category: 'API REST',
    ),
    ExampleItem(
      id: 69,
      title: 'Búsqueda con debounce',
      subtitle: 'TextField + Timer + query params',
      icon: Icons.search,
      route: '/api_search',
      category: 'API REST',
    ),
    ExampleItem(
      id: 70,
      title: 'Manejo de errores',
      subtitle: 'Timeout, 404, 500, sin conexión',
      icon: Icons.error_outline,
      route: '/api_errors',
      category: 'API REST',
    ),
    ExampleItem(
      id: 71,
      title: 'Carga de imágenes',
      subtitle: 'FadeInImage, placeholder, errorBuilder',
      icon: Icons.image,
      route: '/api_images',
      category: 'API REST',
    ),
  ],
  'Google Maps': [
    ExampleItem(
      id: 74,
      title: 'Mapa básico',
      subtitle: 'GoogleMap + CameraPosition + LatLng',
      icon: Icons.map,
      route: '/map_basic',
      category: 'Google Maps',
    ),
    ExampleItem(
      id: 75,
      title: 'MapType — normal, satellite, terrain, hybrid',
      subtitle: 'Cambiar el estilo del mapa en caliente',
      icon: Icons.layers,
      route: '/map_type',
      category: 'Google Maps',
    ),
    ExampleItem(
      id: 76,
      title: 'Cámara — moveCamera vs animateCamera',
      subtitle: 'Control programático, bearing y tilt 3D',
      icon: Icons.my_location,
      route: '/map_camera_control',
      category: 'Google Maps',
    ),
    ExampleItem(
      id: 77,
      title: 'Markers dinámicos',
      subtitle: 'Set<Marker>, onLongPress, InfoWindow',
      icon: Icons.add_location_alt,
      route: '/map_markers',
      category: 'Google Maps',
    ),
    ExampleItem(
      id: 78,
      title: 'InfoWindow',
      subtitle: 'title, snippet, onTap, showMarkerInfoWindow',
      icon: Icons.info_outline,
      route: '/map_info_window',
      category: 'Google Maps',
    ),
    ExampleItem(
      id: 79,
      title: 'Polylines — rutas',
      subtitle: 'Puntos, geodesic, caps, jointType',
      icon: Icons.timeline,
      route: '/map_polylines',
      category: 'Google Maps',
    ),
    ExampleItem(
      id: 80,
      title: 'Polygons — áreas',
      subtitle: 'Polígono cerrado, stroke y fill',
      icon: Icons.crop_square,
      route: '/map_polygons',
      category: 'Google Maps',
    ),
    ExampleItem(
      id: 81,
      title: 'Circles — radios y cobertura',
      subtitle: 'Centro, radio en metros, fillColor',
      icon: Icons.radio_button_unchecked,
      route: '/map_circles',
      category: 'Google Maps',
    ),
    ExampleItem(
      id: 82,
      title: 'Controles de UI y gestures',
      subtitle: 'zoom, rotate, tilt, compass, toolbar, traffic',
      icon: Icons.tune,
      route: '/map_ui_controls',
      category: 'Google Maps',
    ),
    ExampleItem(
      id: 83,
      title: 'My Location + permisos',
      subtitle: 'myLocationEnabled, myLocationButton, simulación permiso',
      icon: Icons.gps_fixed,
      route: '/map_my_location',
      category: 'Google Maps',
    ),
    ExampleItem(
      id: 84,
      title: 'Estilos de mapa (JSON)',
      subtitle: 'setMapStyle, dark mode, onCameraMove',
      icon: Icons.palette,
      route: '/map_styling',
      category: 'Google Maps',
    ),
  ],
};

class HomePage extends StatelessWidget {
  const HomePage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Flutter Demostrador')),
      body: ListView(
        padding: const EdgeInsets.symmetric(vertical: 8),
        children: exampleCategories.entries.expand((entry) {
          return [
            Padding(
              padding: const EdgeInsets.fromLTRB(16, 16, 16, 4),
              child: Text(
                entry.key,
                style: Theme.of(context).textTheme.titleMedium?.copyWith(
                      color: Theme.of(context).colorScheme.primary,
                      fontWeight: FontWeight.bold,
                    ),
              ),
            ),
            ...entry.value.map(
              (item) => ListTile(
                leading: Icon(item.icon),
                title: Text(item.title),
                subtitle: Text(item.subtitle),
                trailing: const Icon(Icons.chevron_right),
                onTap: () => Navigator.of(context).pushNamed(item.route),
              ),
            ),
            const Divider(),
          ];
        }).toList(),
      ),
    );
  }
}